version: '3.9'

services:
  medical_appointment_server:
    container_name: medical_appointment_server
    build:
      context: .
    ports:
      - 8000:8000
    volumes:
      - ./medical_appointment_server:/medical_appointment_server
      - ./data/web/static:/data/web/static/
      - ./data/web/media:/data/web/media/
    env_file:
      - ./dotenv_files/.env
    depends_on:
      - psql
  psql:
    container_name: psql
    image: postgres:13-alpine
    volumes:
      - ./data/postgres/data:/var/lib/postgresql/data/
    env_file:
      - ./dotenv_files/.env